name: Ben Price
favicon: null
layout_spectrum: 0.5875552566722035
typography_spectrum: 0.6957025532610714
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5239136156160384
  lightness: 0.2981172895524651
  saturation: 0.08478880464099348
  rhythmicContrast: 0.6263378451112658
purpose: []
